spring.application.name=spring-config-properties-constructors

#constructor-binding properties:
ctor.explicit.enabled.props.field3=ok
ctor.explicit.enabled.props.field4=ok
ctor.implicit.enabled.props.field3=ok
ctor.implicit.enabled.props.field4=ok
ctor.implicit.scanned.props.field3=ok
ctor.implicit.scanned.props.field4=ok
ctor.explicit.scanned.props.field3=ok
ctor.explicit.scanned.props.field4=ok

# setter-binding properties:
setter.component.props.field1 = false error
setter.component.props.field2 = false error
setter.bean.props.field1 = false error
setter.bean.props.field2 = false error
