spring.application.name=spring-config-properties-constructors

#constructor-binding properties:
ctor.explicit.enabled.props.field3=ok
ctor.explicit.enabled.props.field4=ok
ctor.implicit.enabled.props.field3=ok
ctor.implicit.enabled.props.field4=ok
ctor.implicit.scanned.props.field3=ok
ctor.implicit.scanned.props.field4=ok
ctor.explicit.scanned.props.field3=ok
ctor.explicit.scanned.props.field4=ok

# setter-binding properties: now they are falsely reported as errors
setter.component.props.field1 = value set in application.properties
setter.component.props.field2 = value set in application.properties
setter.imported.props.field1 = value set in application.properties
setter.imported.props.field2 = value set in application.properties
setter.bean.props.field1 = value set in application.properties
setter.bean.props.field2 = value set in application.properties

# the contructor arguments from CPs that use setter binding:
# they are resolved by IDEA, but not by Spring Boot
#setter.bean.props.field3 = should not be bound
#setter.bean.props.field4 = should not be bound
#setter.component.props.field3 = should not be bound
#setter.component.props.field4 = should not be bound
#setter.component.props.field3=should not be bound
#setter.component.props.field4=should not be bound

# record-type @Bean properties: they will be not binded by Spring Boot
record.bean.props.field1=record field1 set in application.properties - will be ignored
record.bean.props.field2=record field2 set in application.properties - will be ignored